### ISSUE TITLE
undefined method `create_index' for #<ActivePinecone::Pinecone:0x0000ffffa2f5bf98> (NoMethodError)

### ISSUE THREAD

**Issue by imstevecho** [moekidev/active_pinecone#4]
Your gem seems to be very promising.
I just followed README, and got this error.

irb(main):002:0> Recipe
=> Recipe
irb(main):003:0> Recipe.init
/usr/local/bundle/gems/active_pinecone-0.1.4/lib/active_pinecone/base.rb:54:in `init': undefined method `create_index' for #<ActivePinecone::Pinecone:0x0000ffffa2f5bf98> (NoMethodError)

      pinecone.create_index({ name: index_name, dimension: ActivePinecone.configuration.dimension, metrics: ActivePinecone.configuration.metrics })
              ^^^^^^^^^^^^^
irb(main):004:0>

**Comment by moekidev** [comment]
How did you run `irb`?
like the follwing?

```
bundle exec irb
```

**Comment by imstevecho** [comment]
> 

I tried it from Rails console. (Rails 7(
I also tried it from irb like below.

```
root@204d129d606a:/usr/src/app# bundle exec irb
irb(main):004:0> require 'active_pinecone'
=> true
irb(main):005:1* class Recipe < ActivePinecone::Base
irb(main):006:1*   vectorizes :title, :body
irb(main):007:0> end
=> [:title, :body]
irb(main):009:1* ActivePinecone.configure do |config|
irb(main):010:1*   config.openai_access_token = ENV.fetch("OPENAI_ACCESS_TOKEN")
irb(main):011:1*   config.pinecone_api_key = ENV.fetch("PINECONE_API_KEY")
irb(main):012:1*   config.pinecone_environment = ENV.fetch("PINECONE_ENVIRONMENT")
irb(main):013:0> end

irb(main):014:0> Recipe.init
/usr/local/bundle/gems/active_pinecone-0.1.4/lib/active_pinecone/base.rb:54:in `init': undefined method `create_index' for #<ActivePinecone::Pinecone:0x0000ffffa373c528> (NoMethodError)

      pinecone.create_index({ name: index_name, dimension: ActivePinecone.configuration.dimension, metrics: ActivePinecone.configuration.metrics })
              ^^^^^^^^^^^^^
	from (irb):14:in `<main>'
	from /usr/local/bundle/gems/irb-1.7.0/exe/irb:9:in `<top (required)>'
	from /usr/local/bundle/bin/irb:25:in `load'
	from /usr/local/bundle/bin/irb:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:492:in `exec'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.4.15/exe/bundle:37:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	... 3 levels...
```

**Comment by moekidev** [comment]
please try:
```
> ::Pinecone::Client
```

**Comment by imstevecho** [comment]
I am not sure what to do.
I would like to see Recipe.init working

**Comment by moekidev** [comment]
I tried it again and it works well. I'll explore the issue a bit.

```
~/d/m/active_pinecone-sandbox ❯❯❯ dotenv -f .env bundle exec irb
irb(main):001:0> require 'active_pinecone'
=> true
irb(main):002:1* class Recipe < ActivePinecone::Base
irb(main):003:1*   vectorizes :title, :body
irb(main):004:0> end
=> [:title, :body]
irb(main):005:1* ActivePinecone.configure do |config|
irb(main):006:1*   config.openai_access_token = ENV.fetch("OPENAI_ACCESS_TOKEN")
irb(main):007:1*   config.pinecone_api_key = ENV.fetch("PINECONE_API_KEY")
irb(main):008:1*   config.pinecone_environment = ENV.fetch("PINECONE_ENVIRONMENT")
irb(main):009:0> end
=> "us-central1-gcp"
irb(main):010:0> Recipe.init
=> #<HTTParty::Response:0x2be30 parsed_response=nil, @response=#<Net::HTTPCreated 201 Created readbody=true>, @headers={"date"=>["Wed, 05 Jul 2023 03:44:38 GMT"], "x-envoy-upstream-service-time"=>["578"], "content-length"=>["0"], "server"=>["envoy"], "connection"=>["close"]}>
irb(main):011:0> 
```

**Comment by imstevecho** [comment]
This is what I see.

```
root@204d129d606a:/usr/src/app# dotenv -f .env bundle exec irb
irb(main):001:0> require 'active_pinecone'
=> true
irb(main):002:1* ActivePinecone.configure do |config|
irb(main):003:1*   config.openai_access_token = ENV.fetch("OPENAI_ACCESS_TOKEN")
irb(main):004:1*   config.pinecone_api_key = ENV.fetch("PINECONE_API_KEY")
irb(main):005:1*   config.pinecone_environment = ENV.fetch("PINECONE_ENVIRONMENT")
irb(main):006:0> end
=> "us-central1-gcp"
irb(main):007:1* class Recipe < ActivePinecone::Base
irb(main):008:1*   vectorizes :title, :body
irb(main):009:0> end
=> [:title, :body]
irb(main):010:0> Recipe.init
/usr/local/bundle/gems/active_pinecone-0.1.4/lib/active_pinecone/base.rb:54:in `init': undefined method `create_index' for #<ActivePinecone::Pinecone:0x0000ffff9a224b70> (NoMethodError)

      pinecone.create_index({ name: index_name, dimension: ActivePinecone.configuration.dimension, metrics: ActivePinecone.configuration.metrics })
              ^^^^^^^^^^^^^
	from (irb):10:in `<main>'
	from /usr/local/bundle/gems/irb-1.7.0/exe/irb:9:in `<top (required)>'
	from /usr/local/bundle/bin/irb:25:in `load'
	from /usr/local/bundle/bin/irb:25:in `<top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `load'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:23:in `run'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:492:in `exec'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:34:in `dispatch'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli.rb:28:in `start'
	from /usr/local/bundle/gems/bundler-2.4.15/exe/bundle:37:in `block in <top (required)>'
	from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	... 3 levels...
irb(main):011:0>
```
